name: "Archiver Actions"

description: "Archive or restore a build in the vault"

inputs:
  actionType:
    description: "Action type"
    required: true
  version:
    description: "Version of the build"
    required: true
  appName:
    description: "Application name"
    required: true
  deviceType:
    description: "Device type"
    required: true
  environment:
    description: "Environment type"
    required: true
  folderPath:
    description: "Path to the folder to archive/restore"
    required: false
  filePath:
    description: "Path to the file to archive/restore"
    required: false

outputs:
  errorMessage:
    description: 'Error message if the action fails'
  remoteFolderContent:
    description: 'Updated versions available for this device'

runs:
  using: "docker"
  image: "Dockerfile"

steps:
  - name: Check action type and push new file if needed
    run: |
      if [ "${{ inputs.actionType }}" == "store-folder" ]; then
        # Add your logic here for the fake-action
        # For example, create a new file and push to the repository
        echo "Commit changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update versions"
        git push
      else
        echo "Action type not recognized or no action needed for this type."
      fi